// Generated by gencpp from file jetracer/jetRacerCar.msg
// DO NOT EDIT!


#ifndef JETRACER_MESSAGE_JETRACERCAR_H
#define JETRACER_MESSAGE_JETRACERCAR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jetracer
{
template <class ContainerAllocator>
struct jetRacerCar_
{
  typedef jetRacerCar_<ContainerAllocator> Type;

  jetRacerCar_()
    : steerAngle(0.0)
    , throttle(0.0)  {
    }
  jetRacerCar_(const ContainerAllocator& _alloc)
    : steerAngle(0.0)
    , throttle(0.0)  {
  (void)_alloc;
    }



   typedef float _steerAngle_type;
  _steerAngle_type steerAngle;

   typedef float _throttle_type;
  _throttle_type throttle;





  typedef boost::shared_ptr< ::jetracer::jetRacerCar_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jetracer::jetRacerCar_<ContainerAllocator> const> ConstPtr;

}; // struct jetRacerCar_

typedef ::jetracer::jetRacerCar_<std::allocator<void> > jetRacerCar;

typedef boost::shared_ptr< ::jetracer::jetRacerCar > jetRacerCarPtr;
typedef boost::shared_ptr< ::jetracer::jetRacerCar const> jetRacerCarConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jetracer::jetRacerCar_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jetracer::jetRacerCar_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jetracer::jetRacerCar_<ContainerAllocator1> & lhs, const ::jetracer::jetRacerCar_<ContainerAllocator2> & rhs)
{
  return lhs.steerAngle == rhs.steerAngle &&
    lhs.throttle == rhs.throttle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jetracer::jetRacerCar_<ContainerAllocator1> & lhs, const ::jetracer::jetRacerCar_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jetracer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jetracer::jetRacerCar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jetracer::jetRacerCar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetracer::jetRacerCar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jetracer::jetRacerCar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetracer::jetRacerCar_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jetracer::jetRacerCar_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jetracer::jetRacerCar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aff191fd10fed555ff6297c6aea6a03a";
  }

  static const char* value(const ::jetracer::jetRacerCar_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaff191fd10fed555ULL;
  static const uint64_t static_value2 = 0xff6297c6aea6a03aULL;
};

template<class ContainerAllocator>
struct DataType< ::jetracer::jetRacerCar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jetracer/jetRacerCar";
  }

  static const char* value(const ::jetracer::jetRacerCar_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jetracer::jetRacerCar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 steerAngle\n"
"float32 throttle\n"
;
  }

  static const char* value(const ::jetracer::jetRacerCar_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jetracer::jetRacerCar_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.steerAngle);
      stream.next(m.throttle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct jetRacerCar_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jetracer::jetRacerCar_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jetracer::jetRacerCar_<ContainerAllocator>& v)
  {
    s << indent << "steerAngle: ";
    Printer<float>::stream(s, indent + "  ", v.steerAngle);
    s << indent << "throttle: ";
    Printer<float>::stream(s, indent + "  ", v.throttle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JETRACER_MESSAGE_JETRACERCAR_H
